### ISSUE TITLE
Bug version 1.4.1

### ISSUE THREAD

**Issue by Dominique56** [omeka-s-themes/papers#21]
Version 1.4.1 does not work with Omeka S V4
Here is the error message
TypeError: Omeka\Api\Representation
\AbstractResourceEntityRepresentation::displaySubjectValues(): Argument #1
($options) must be of type array, int given, called in /bsd/themes/papers/
view/omeka/site/item/show.phtml on line 50 and defined in bsd/application/src/API/Representation/AbstractResourceEntityRepresentation.php:523
Stack trace:
#0 bsd/themes/papers/view/omeka/site/item/show.phtml(50): Omeka\Api\RepresentationAbstractResourceEntityRepresentation->displaySubjectValues()
#1 bsd/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519):
include('/home/alla6772/...')
#2 bsd/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render()
#3 bsd/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View-> render()
#4 bsd/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View-> renderChildren()
#5 bsd/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render()
#6 bsd/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas
\Mvc\View\Http\DefaultRenderingStrategy->render()
#7 bsd/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas
\EventManager\EventManager->triggerListeners()
#8 bsd/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas
\EventManager\EventManager->triggerEvent()
#9 bsd/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc
\Application->completeRequest()
#10 bsd/index.php(21): Laminas\Mvc\Application->run()
#11 {hand
Thank you for your help

**Comment by Dominique56** [comment]
the bug is fixed, bad update of the theme
Sorry
